### ISSUE TITLE
MagazineThumb error

### ISSUE THREAD

**Issue by kukusumaa** [bakerframework/baker-android#14]
Hi, im new in baker android.
I have follow the process on https://github.com/bakerframework/baker-android/wiki/Creating-your-own-Baker-Android-Project.
But i still have a problem. What i should do on my java folder? I mean, did i have to copied all of the files on Java folder from ABakerProject?
Because, i've try to copied all of the java files on ABakerProject but i still have an error like this : Cannot find symbol constructor BookJsonParserTask(com.myproject.ok.views.MagazineThumb)
Could somebody help me please?

**Comment by brainedia** [comment]
Im sorry to reopen this thread, but I get the same error, while having my emulator setup with an 1GB SDCard.

```
(...)
04-29 10:19:46.698    2693-2693/com.example.MyApp D/﹕ HostConnection::get() New Host Connection established 0xa6004ad0, tid 2693
04-29 10:19:46.971    2693-2693/com.example.MyApp W/chromium﹕ [WARNING:mailbox_synchronizer.cc(36)] MailboxSync not supported due to missing EGL image/fence support
04-29 10:19:47.019    2693-2720/com.example.MyApp W/chromium﹕ [WARNING:proxy_service.cc(901)] PAC support disabled because there is no system implementation
04-29 10:19:47.026    2693-2693/com.example.MyApp W/chromium﹕ [WARNING:data_reduction_proxy_settings.cc(403)] SPDY proxy OFF at startup
04-29 10:19:47.055    2693-2693/com.example.MyApp W/art﹕ Attempt to remove local handle scope entry from IRT, ignoring
04-29 10:19:47.060    2693-2693/com.example.MyApp W/AwContents﹕ onDetachedFromWindow called when already detached. Ignoring
04-29 10:19:47.172    2693-2693/com.example.MyApp E/class com.baker.abaker.GindActivity﹕ USER ACCOUNT COULD NOT BE RETRIEVED, WILL USE ANDROID_ID.
04-29 10:19:47.176    2693-2693/com.example.MyApp D/com.baker.abaker.GindActivity﹕ APP_ID: Baker Android, USER_ID: 3a143b1503f6a59b
04-29 10:19:47.203    2693-2693/com.example.MyApp D/com.baker.abaker.GindActivity﹕ Google Play Services enabled.
04-29 10:19:47.232    2693-2693/com.example.MyApp D/class com.baker.abaker.GindActivity﹕ Registration ID not found.
04-29 10:19:47.232    2693-2693/com.example.MyApp D/com.baker.abaker.GindActivity﹕ Obtained registration ID:
04-29 10:19:47.260    2693-2734/com.example.MyApp D/OpenGLRenderer﹕ Render dirty regions requested: true
04-29 10:19:47.278    2693-2693/com.example.MyApp D/Atlas﹕ Validating map...
04-29 10:19:47.347    2693-2700/com.example.MyApp I/art﹕ Background partial concurrent mark sweep GC freed 691(81KB) AllocSpace objects, 3(48KB) LOS objects, 40% free, 4MB/7MB, paused 634us total 222.383ms
04-29 10:19:47.373    2693-2734/com.example.MyApp I/OpenGLRenderer﹕ Initialized EGL, version 1.4
04-29 10:19:47.373    2693-2734/com.example.MyApp D/﹕ HostConnection::get() New Host Connection established 0xa40160d0, tid 2734
04-29 10:19:47.405    2693-2734/com.example.MyApp D/OpenGLRenderer﹕ Enabling debug mode 0
04-29 10:19:47.437    2693-2734/com.example.MyApp W/EGL_emulation﹕ eglSurfaceAttrib not implemented
04-29 10:19:47.437    2693-2734/com.example.MyApp W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa429f680, error=EGL_SUCCESS
04-29 10:19:48.178    2693-2733/com.example.MyApp E/class com.baker.abaker.workers.GCMRegistrationWorker﹕ Error generating the registration ID: INVALID_PARAMETERS
04-29 10:19:48.178    2693-2733/com.example.MyApp W/System.err﹕ java.io.IOException: INVALID_PARAMETERS
04-29 10:19:48.181    2693-2733/com.example.MyApp W/System.err﹕ at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
04-29 10:19:48.181    2693-2733/com.example.MyApp W/System.err﹕ at com.baker.abaker.workers.GCMRegistrationWorker.doInBackground(GCMRegistrationWorker.java:53)
04-29 10:19:48.182    2693-2733/com.example.MyApp W/System.err﹕ at com.baker.abaker.workers.GCMRegistrationWorker.doInBackground(GCMRegistrationWorker.java:24)
04-29 10:19:48.182    2693-2733/com.example.MyApp W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:288)
04-29 10:19:48.182    2693-2733/com.example.MyApp W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-29 10:19:48.182    2693-2733/com.example.MyApp W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
04-29 10:19:48.182    2693-2733/com.example.MyApp W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-29 10:19:48.182    2693-2733/com.example.MyApp W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-29 10:19:48.182    2693-2733/com.example.MyApp W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
04-29 10:19:48.190    2693-2737/com.example.MyApp D/com.baker.abaker.workers.CheckInternetTask﹕ Starting process to check for an internet connection.
04-29 10:19:48.191    2693-2737/com.example.MyApp D/class com.baker.abaker.workers.CheckInternetTask﹕ TESTING INTERNET CONNECTION WITH HOST http://google.com AND TIMEOUT 15000
04-29 10:19:48.315    2693-2693/com.example.MyApp D/class com.baker.abaker.GindActivity﹕ Could not create registration ID for GCM services
04-29 10:19:48.562    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
04-29 10:19:48.575    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
04-29 10:19:48.579    2693-2737/com.example.MyApp D/class com.baker.abaker.workers.CheckInternetTask﹕ THE TESTING INTERNET CONNECTION STATUS CODE WAS 200
04-29 10:19:48.579    2693-2737/com.example.MyApp D/class com.baker.abaker.workers.CheckInternetTask﹕ HAS INTERNET CONNECTION: TRUE
04-29 10:19:48.632    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:48.632    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:48.637    2693-2693/com.example.MyApp D/class com.baker.abaker.GindActivity﹕ FINISHED TESTING INTERNET CONNECTION, CHECKING SHELF...
04-29 10:19:48.640    2693-2693/com.example.MyApp D/>>>CONFIGURATION﹕ EXTERNAL STORAGE IS *NOT* MOUNTED FOR CACHE.
04-29 10:19:48.641    2693-2693/com.example.MyApp D/class com.baker.abaker.GindActivity﹕ Internet access available but shelf does not exist.
04-29 10:19:48.643    2693-2693/com.example.MyApp D/>>>CONFIGURATION﹕ EXTERNAL STORAGE IS *NOT* MOUNTED FOR CACHE.
04-29 10:19:48.653    2693-2733/com.example.MyApp D/class com.baker.abaker.workers.DownloaderTask﹕ DownloaderTask will overwrite the file /data/data/com.example.MyApp/cache/shelf.json
04-29 10:19:48.660    2693-2733/com.example.MyApp D/class com.baker.abaker.workers.DownloaderTask﹕ USING RELATIVE PATH FOR DOWNLOAD: /data/data/com.example.MyApp/cache
04-29 10:19:48.666    2693-2733/com.example.MyApp E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #1
    Process: com.example.MyApp, PID: 2693
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.SecurityException: Destination must be on external storage: file:///data/data/com.example.MyApp/cache/shelf.json
            at android.os.Parcel.readException(Parcel.java:1540)
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
            at android.content.ContentProviderProxy.insert(ContentProviderNative.java:475)
            at android.content.ContentResolver.insert(ContentResolver.java:1207)
            at android.app.DownloadManager.enqueue(DownloadManager.java:946)
            at com.baker.abaker.workers.DownloaderTask.doInBackground(DownloaderTask.java:174)
            at com.baker.abaker.workers.DownloaderTask.doInBackground(DownloaderTask.java:19)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
04-29 10:19:49.089    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
04-29 10:19:49.090    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
04-29 10:19:49.191    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:49.191    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:49.204    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
04-29 10:19:49.205    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
04-29 10:19:49.208    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:49.208    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:49.209    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
04-29 10:19:49.210    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
04-29 10:19:49.211    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:49.211    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:49.348    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
04-29 10:19:49.349    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
04-29 10:19:50.831    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:50.831    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:51.033    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
04-29 10:19:51.096    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
04-29 10:19:51.100    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:51.100    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:51.103    2693-2693/com.example.MyApp I/Choreographer﹕ Skipped 107 frames!  The application may be doing too much work on its main thread.
04-29 10:19:51.103    2693-2693/com.example.MyApp D/com.baker.abaker.GindActivity﹕ onDestroy method invoked!
04-29 10:19:51.199    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
04-29 10:19:51.199    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
04-29 10:19:51.229    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:51.229    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:51.392    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
04-29 10:19:51.398    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
04-29 10:19:51.401    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:51.401    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:51.403    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
04-29 10:19:51.405    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
04-29 10:19:51.420    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:51.420    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:51.422    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
04-29 10:19:51.423    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
04-29 10:19:51.429    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:51.429    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:51.430    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
04-29 10:19:51.431    2693-2734/com.example.MyApp E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
04-29 10:19:51.432    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:51.433    2693-2734/com.example.MyApp E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
04-29 10:19:56.140    2693-2697/com.example.MyApp W/CursorWrapperInner﹕ Cursor finalized without prior close()
04-29 10:19:56.142    2693-2697/com.example.MyApp W/CursorWrapperInner﹕ Cursor finalized without prior close()
04-29 10:19:56.859    2693-2733/com.example.MyApp I/Process﹕ Sending signal. PID: 2693 SIG: 9
```
