### ISSUE TITLE
Error parsing the book.json

### ISSUE THREAD

**Issue by edy-fulqentius** [bakerframework/baker-android#83]
Hi,

I'm using baker framework for android, I got some error when I set the app run as standalone mode bellow is the error log

01-09 04:19:04.085    1670-1691/? E/com.baker.abaker.workers.BookJsonParserTask﹕ Error parsing the book.json.
    java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.baker.abaker.test/files/magazines/issues/book.json: open failed: ENOENT (No such file or directory)
            at libcore.io.IoBridge.open(IoBridge.java:416)
            at java.io.FileInputStream.<init>(FileInputStream.java:78)
            at java.io.FileInputStream.<init>(FileInputStream.java:105)
            at com.baker.abaker.workers.BookJsonParserTask.doInBackground(BookJsonParserTask.java:108)
            at com.baker.abaker.workers.BookJsonParserTask.doInBackground(BookJsonParserTask.java:27)
            at android.os.AsyncTask$2.call(AsyncTask.java:287)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
            at libcore.io.Posix.open(Native Method)
            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
            at libcore.io.IoBridge.open(IoBridge.java:400)
            at java.io.FileInputStream.<init>(FileInputStream.java:78)
            at java.io.FileInputStream.<init>(FileInputStream.java:105)
            at com.baker.abaker.workers.BookJsonParserTask.doInBackground(BookJsonParserTask.java:108)
            at com.baker.abaker.workers.BookJsonParserTask.doInBackground(BookJsonParserTask.java:27)
            at android.os.AsyncTask$2.call(AsyncTask.java:287)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)

I put all the content in the book asset folder.

The app working good if I set the app as a newstand app, any comment and suggest is welcome.

NB : I used the same book.json with what I used for baker for iOs

Thanks for your help :)

**Comment by hsalazarl** [comment]
Hello @edy-fulqentius,

Thanks for the feedback, yes, we detected the problem and added a fix for it, sorry for any inconvenience. Please download the latest code and give it a try.

Best regards.

**Comment by edy-fulqentius** [comment]
Hello @hsalazarl 

I got fixed by change the value from parser.setFromAssets(false); to true

But I think better I download the latest version :)

Thanks
